const avatarOptions = [
  "/avatars/avatar2.png",
  "/avatars/avatar1.png",
  "/avatars/avatar3.png",
  "/avatars/avatar4.png",
  "/avatars/avatar5.png",
  "/avatars/avatar6.png",
  "/avatars/avatar7.png",
  "/avatars/avatar8.png",
  "/avatars/avatar9.png",
  "/avatars/avatar10.png",
  "/avatars/avatar11.png",
  "/avatars/avatar12.png",
  "/avatars/avatar13.png",
  "/avatars/avatar14.png",
  "/avatars/avatar15.png",
  "/avatars/avatar16.png",
  "/avatars/avatar17.png",
  "/avatars/avatar18.png",
  "/avatars/avatar19.png",
  "/avatars/avatar20.png",
  "/avatars/avatar21.png",
  "/avatars/avatar22.png",
  "/avatars/avatar23.png",
  "/avatars/avatar24.png",
  "/avatars/avatar25.png",
  "/avatars/avatar26.png",
  "/avatars/avatar27.png",
  "/avatars/avatar28.png",
  "/avatars/avatar29.png",
];

const moralValues = [
  "Honesty: Always tell the truth",
  "Respect: Treat others with kindness",
  "Responsibility: Own your actions",
  "Fairness: Act with justice",
  "Compassion: Care for others",
  "Courage: Stand up for what's right",
  "Gratitude: Be thankful",
  "Humility: Stay modest",
  "Perseverance: Keep going",
  "Forgiveness: Let go of grudges",
  "Integrity: Do what is right",
  "Empathy: Understand others' feelings",
  "Generosity: Share with others",
  "Patience: Wait calmly",
  "Kindness: Be friendly and considerate",
  "Loyalty: Be faithful to commitments",
  "Trustworthiness: Keep your promises",
  "Diligence: Work hard consistently",
  "Tolerance: Accept differences",
  "Wisdom: Make thoughtful decisions",
  "Self-discipline: Control your actions",
  "Optimism: Stay positive",
  "Sincerity: Be genuine",
  "Charity: Help those in need",
  "Justice: Uphold what is fair",
  "Honor: Act with dignity",
  "Prudence: Plan carefully",
  "Graciousness: Be polite and courteous",
  "Determination: Stay focused on goals",
  "Altruism: Put others first",
  "Reliability: Be dependable",
  "Civility: Act with respect",
  "Hope: Believe in better days",
  "Mercy: Show compassion to wrongdoers",
  "Steadfastness: Remain firm",
  "Temperance: Practice moderation",
  "Fortitude: Face challenges bravely",
  "Understanding: Listen to others",
  "Peacefulness: Promote calm",
  "Cooperation: Work well with others",
  "Faithfulness: Stay true",
  "Gentleness: Be soft in approach",
  "Humbleness: Avoid arrogance",
  "Tenacity: Hold on through hardship",
  "Sympathy: Share others' sorrows",
  "Vigilance: Stay alert",
  "Chastity: Practice purity",
  "Zeal: Pursue goals eagerly",
  "Meekness: Be gentle and mild",
  "Candor: Speak openly",
  "Contentment: Be satisfied",
  "Decency: Act appropriately",
  "Earnestness: Be serious in effort",
  "Frugality: Use resources wisely",
  "Hospitality: Welcome others warmly",
  "Ingenuity: Be creative",
  "Joyfulness: Spread happiness",
  "Liberality: Give freely",
  "Magnanimity: Be noble in spirit",
  "Obedience: Follow just rules",
  "Piety: Show reverence",
  "Purity: Maintain clean intentions",
  "Resilience: Bounce back",
  "Selflessness: Prioritize others",
  "Simplicity: Live plainly",
  "Solidarity: Stand together",
  "Thrift: Save wisely",
  "Unity: Foster togetherness",
  "Valiance: Show bravery",
  "Veracity: Speak truthfully",
  "Virtue: Uphold moral excellence",
  "Warmth: Be approachable",
  "Zealousness: Act with passion",
  "Adaptability: Adjust to change",
  "Benevolence: Wish others well",
  "Clarity: Communicate clearly",
  "Commitment: Stay dedicated",
  "Courtesy: Be polite",
  "Devotion: Be deeply committed",
  "Discernment: Judge wisely",
  "Equanimity: Stay balanced",
  "Fidelity: Be loyal",
  "Friendliness: Be amicable",
  "Inclusivity: Embrace all",
  "Mindfulness: Be present",
  "Openness: Be receptive",
  "Reverence: Show deep respect",
  "Sacrifice: Give up for others",
  "Serenity: Stay calm",
  "Stewardship: Care for resources",
  "Tact: Speak thoughtfully",
  "Transparency: Be open",
  "Uprightness: Act morally",
  "Vitality: Live energetically",
  "Wholeness: Seek balance",
  "Yearning: Strive for good",
  "Zest: Live with enthusiasm",
];

export const moralStories = [
  {
    title: "Fighting Goats and the Jackal",
    content: [
      "One day while a sage was going through a jungle, he saw two golden rams (billy goats) fighting each other. Even though both were wounded, and blood was oozing out from their heads and bodies, they did not stop fighting and rammed at each other.",
      `At the same time, a hungry jackal was passing by. When he saw all the blood, he started licking the blood from the ground without caring for the fighting rams. Watching all this, the sage thought to himself, "This jackal is a fool as it has become greedy by the smell of blood. If he comes between the fighting rams, it will get rammed and get hurt himself".`,
      "No sooner had the sage thought of it, the jackal craving for more blood came nearer to the fighting rams, and got caught in the middle of their fight.Both the rams rammed into him by mistake. He got hit on his head, and fell down because he was severely wounded.",
    ],
    images: [
      {
        url: "/stories/Fighting Goats and the Jackal_1.png",
        alt: "Fighting Goats and the Jackal",
      },
      {
        url: "/stories/Fighting Goats and the Jackal_2.png",
        alt: "Fighting Goats and the Jackal",
      },
    ],
    moral: "Do not close your eyes to the impending danger due to greed.",
  },
  {
    title: "The King and the Foolish Monkey",
    content: [
      "Once there was a king, who had a pet monkey.This monkey was a fool, but was treated royally and moved freely in the king's palace. He was also allowed to enter the king's personal rooms that were forbidden even for the confidential servants.",
      `One afternoon, the king was asleep, while the monkey kept a watch. All of a sudden, a fly came in the room and sat on the king's chest. The monkey swayed her away, but the fly would only go away for some time and return on the king's chest again.`,
      "The monkey got very angry and excited. The foolish monkey started chasing the fly with a sword. As the fly sat on the king's chest again, the monkey hit the fly with all his might. The fly flew away unharmed, but the king was severely wounded.",
    ],
    images: [
      {
        url: "/stories/The King and the Foolish Monkey_1.png",
        alt: "The King and the Foolish Monkey",
      },
      {
        url: "/stories/The King and the Foolish Monkey_2.png",
        alt: "The King and the Foolish Monkey",
      },
    ],
    moral:
      "Beware of a foolish friend. He can cause you more harm than your enemy.",
  },
  {
    title: "The Bird with Two Heads",
    content: [
      `Once upon a time, there lived a great bird named Bharunda, on the banks of a lake. It was strange because he had two necks with two heads, but shared the common body. One day, as the bird was wandering, it found a delicious looking red-golden fruit. One of the heads mumbled, "Oh, what a delicious looking fruit. I am lucky to have found it. I am sure the fruit is sent from heavens only for me". On saying so, it started eating the fruit with utmost pleasure. While eating, it kept on praising how it was the most delicious fruit he had ever eaten. Hearing and seeing all this, the other head requested, "Oh dear, please also allow me to taste the fruit that you are praising with all your heart".`,
      `The first head did not want to share it, so it laughed and said, "We share the same stomach. Whoever amongst us eats the fruit, it goes to the same stomach. It makes no difference on who eats the fruit. Moreover, since I am the one who found this fruit in the first place, I have the right to eat it myself." This selfishness of the first head hurt him very much, and he went silent with disappointment on hearing the first head's reply.`,
      `Few days later, as they were wandering the second head found some fruits. The fruits were from a poisonous tree. He declared to the first head, "You are a deceitful person. The other day you had insulted me by not sharing the delicious fruit. Now I am going to eat this fruit and avenge your insult". The first head pleaded, "Please don't eat this fruit, it is a poisonous one. We share the same stomach. If you eat it, we will both suffer" Mocking at the first head, the second head replied, "Shut up! Since I am the one who found this fruit in the first place, I have the right to eat it myself". Knowing what would happen, the first head began to cry. The second head ate the poisonous fruit without bothering the first head's requests. As a consequence of this action, as soon as the poison reached the stomach, the bird severely suffered.`,
    ],
    images: [
      {
        url: "/stories/The Bird with Two Heads_1.png",
        alt: "The Bird with Two Heads",
      },
      {
        url: "/stories/The Bird with Two Heads_2.png",
        alt: "The Bird with Two Heads",
      },
    ],
    moral:
      "Union is strength.",
  },
  {
    title: "The Bird and the Monkey",
    content: [
      `There lived a group of monkeys in the mountains. During one winter, there were heavy rains. Drenched in the rain, they began to shiver in the cold. During this time, some of the monkey found some colourful Gunja fruits, which appeared to them as embers of fire. Hoping to make some fire for themselves, they began to blow at them. A bird on a nearby tree was watching the monkeys from above. Considering the vain attempts the monkeys were busy with, it thought of advising them against it, "What big fools you are. You are blowing at some Gunja fruits and not embers of fire. You will never be able to make any fire out of them."`,
      `"What you are doing is a waste of time. These fruits will not help you to protect yourself against the cold. Go and find some shelter instead. You may find a cave or a burrow where you will be protected from the rains and the cold winds." The monkeys did not like his advice. One of the old monkeys said, "Go fool yourself. Why are you interfering in our task?" But the bird disagreed. Not heeding what the old monkey had said, it flew down from the tree and persisted that the monkeys stop what they were doing. The monkey ignored his chatter but the bird refused to stop.`,
      `In an effort to convince the monkeys, the bird came close to explain that their efforts were useless. Already frustrated by their vain efforts, the monkeys became furious. One of the monkeys caught hold of the bird and smashed him against the ground. The bird was severely wounded.`,
    ],
    images: [
      {
        url: "/stories/The Bird and the Monkey_1.png",
        alt: "The Bird and the Monkey",
      },
      {
        url: "/stories/The Bird and the Monkey_2.png",
        alt: "The Bird and the Monkey",
      },
    ],
    moral:
      "Never give advice unless you are asked for it.",
  },
  {
    title: "The Monkey and the Wedge",
    content: [
      `There was once a merchant who employed many carpenters and masons to build a temple in his garden. Regularly, they would start work in the morning; and take a break for the mid-day meals, and return to resume work till evening. One day, a group of monkey arrived at the site of the building and watched the workers leaving for their mid-day meals. One of the carpenters was sawing a huge log of wood. Since, it was only half-done; he placed a wedge in between to prevent the log from closing up. He then went off along with the other workers for his meal.`,
      `When all the workers were gone, the monkeys came down from the trees and started jumping around the site, and playing with the instruments. There was one monkey, who got curious about the wedge placed between the log. He sat down on the log, and having placed himself in between the half-split log, caught hold of the wedge and started pulling at it.`,
      `All of a sudden, the wedge came out. As a result, the half-split log closed in and the monkey got caught in the gap of the log. As was his destiny, he was severely wounded.`,
    ],
    images: [
      {
        url: "/stories/The Monkey and the Wedge_1.png",
        alt: "The Monkey and the Wedge",
      },
      {
        url: "/stories/The Monkey and the Wedge_2.png",
        alt: "The Monkey and the Wedge",
      },
    ],
    moral:
      "One, who interferes in other's work, surely comes to grief.",
  },
];

const containerClasses =
  "flex flex-col items-center min-h-screen bg-[#f8f7f6] px-4 font-[family-name:var(--font-geist-sans)]";
const headerClasses =
  "w-full flex justify-between px-4 lg:px-32 items-center py-4 fixed bg-[#f8f7f6]";
const buttonWrapperClasses = "flex items-center gap-2 cursor-pointer";
const buttonClasses =
  "flex items-center gap-2 bg-white rounded-full py-2 px-4 shadow-sm hover:bg-gray-100 transition-colors text-lg text-gray-900 cursor-pointer";

export {
  avatarOptions,
  containerClasses,
  headerClasses,
  buttonWrapperClasses,
  buttonClasses,
  moralValues,
};
