const avatarOptions = [
  "/avatars/avatar2.png",
  "/avatars/avatar1.png",
  "/avatars/avatar3.png",
  "/avatars/avatar4.png",
  "/avatars/avatar5.png",
  "/avatars/avatar6.png",
  "/avatars/avatar7.png",
  "/avatars/avatar8.png",
  "/avatars/avatar9.png",
  "/avatars/avatar10.png",
  "/avatars/avatar11.png",
  "/avatars/avatar12.png",
  "/avatars/avatar13.png",
  "/avatars/avatar14.png",
  "/avatars/avatar15.png",
  "/avatars/avatar16.png",
  "/avatars/avatar17.png",
  "/avatars/avatar18.png",
  "/avatars/avatar19.png",
  "/avatars/avatar20.png",
  "/avatars/avatar21.png",
  "/avatars/avatar22.png",
  "/avatars/avatar23.png",
  "/avatars/avatar24.png",
  "/avatars/avatar25.png",
  "/avatars/avatar26.png",
  "/avatars/avatar27.png",
  "/avatars/avatar28.png",
  "/avatars/avatar29.png",
];

const moralValues = [
  "Honesty: Always tell the truth",
  "Respect: Treat others with kindness",
  "Responsibility: Own your actions",
  "Fairness: Act with justice",
  "Compassion: Care for others",
  "Courage: Stand up for what's right",
  "Gratitude: Be thankful",
  "Humility: Stay modest",
  "Perseverance: Keep going",
  "Forgiveness: Let go of grudges",
  "Integrity: Do what is right",
  "Empathy: Understand others' feelings",
  "Generosity: Share with others",
  "Patience: Wait calmly",
  "Kindness: Be friendly and considerate",
  "Loyalty: Be faithful to commitments",
  "Trustworthiness: Keep your promises",
  "Diligence: Work hard consistently",
  "Tolerance: Accept differences",
  "Wisdom: Make thoughtful decisions",
  "Self-discipline: Control your actions",
  "Optimism: Stay positive",
  "Sincerity: Be genuine",
  "Charity: Help those in need",
  "Justice: Uphold what is fair",
  "Honor: Act with dignity",
  "Prudence: Plan carefully",
  "Graciousness: Be polite and courteous",
  "Determination: Stay focused on goals",
  "Altruism: Put others first",
  "Reliability: Be dependable",
  "Civility: Act with respect",
  "Hope: Believe in better days",
  "Mercy: Show compassion to wrongdoers",
  "Steadfastness: Remain firm",
  "Temperance: Practice moderation",
  "Understanding: Listen to others",
  "Humility: Sweetness of speech and humility in nature makes a person successful and great - Chanakya",
  "Humility: A tree laden with fruits always bends low. Humility is a sign of greatness - Ramakrishna Paramahamsa",
  "Humility: The more we are humble, the better it is for us - - Ramana Maharshi",
  "Fortitude: Face challenges bravely",
  "Peacefulness: Promote calm",
  "Cooperation: Work well with others",
  "Faithfulness: Stay true",
  "Gentleness: Be soft in approach",
  "Humbleness: Avoid arrogance",
  "Tenacity: Hold on through hardship",
  "Sympathy: Share others' sorrows",
  "Vigilance: Stay alert",
  "Chastity: Practice purity",
  "Zeal: Pursue goals eagerly",
  "Meekness: Be gentle and mild",
  "Candor: Speak openly",
  "Contentment: Be satisfied",
  "Decency: Act appropriately",
  "Earnestness: Be serious in effort",
  "Frugality: Use resources wisely",
  "Hospitality: Welcome others warmly",
  "Ingenuity: Be creative",
  "Joyfulness: Spread happiness",
  "Liberality: Give freely",
  "Magnanimity: Be noble in spirit",
  "Obedience: Follow just rules",
  "Piety: Show reverence",
  "Purity: Maintain clean intentions",
  "Resilience: Bounce back",
  "Selflessness: Prioritize others",
  "Simplicity: Live plainly",
  "Solidarity: Stand together",
  "Thrift: Save wisely",
  "Unity: Foster togetherness",
  "Valiance: Show bravery",
  "Veracity: Speak truthfully",
  "Virtue: Uphold moral excellence",
  "Warmth: Be approachable",
  "Zealousness: Act with passion",
  "Adaptability: Adjust to change",
  "Benevolence: Wish others well",
  "Clarity: Communicate clearly",
  "Commitment: Stay dedicated",
  "Courtesy: Be polite",
  "Devotion: Be deeply committed",
  "Discernment: Judge wisely",
  "Equanimity: Stay balanced",
  "Fidelity: Be loyal",
  "Friendliness: Be amicable",
  "Inclusivity: Embrace all",
  "Mindfulness: Be present",
  "Openness: Be receptive",
  "Reverence: Show deep respect",
  "Sacrifice: Give up for others",
  "Serenity: Stay calm",
  "Stewardship: Care for resources",
  "Tact: Speak thoughtfully",
  "Transparency: Be open",
  "Uprightness: Act morally",
  "Vitality: Live energetically",
  "Wholeness: Seek balance",
  "Yearning: Strive for good",
  "Zest: Live with enthusiasm",
];

export const moralStories = [
  {
    title: "A Journey Beyond the Pitch",
    content: [
      "Rajesh,  a fourteen year old boy studying in class IX was eagerly looking forward to getting into the School 's cricket team. With the selections only a week away, his anxiety quadrapled . He shared his feelings with his mother, who noticed that he was not feeling well. She told him about an incident from the Ramayana, where Lord Hanuman was unsure whether he could cross the mighty ocean, but could do so after being motivated by Jambavan, the king of the bear tribe. She emphasized on the fact that even a person such as Lord Hanuman, who was strong and wise, could have self - doubt . What is important is to defeat the demon called self - doubt and trust your skills.",
      `Rajesh gave his best during the trials. The school team' s coach was impressed. He made Rajesh the captain of the school team. As he was the new ' wonder kid ' in school, he started ignoring his close friends. He spoke rudely to them and was also rude to his mother. His haughtiness became painful to his parents and friends. He stopped going to practice as he thought he had the talent to score well without practice. His friends stopped coming to his matches. Rajesh performed poorly in the tournament. Looking at his poor performance, the cricket coach informed Rajesh that he would not longer be a part of the school team. He felt disheartened and cried profusely to his mother. She calmly listened and consoled him. Rajesh understood that during the selection trials,  what enabled him to perform well was not only his talent but also,`,
      ` -- consistent practice, `,
      `-- the unconditional support that his friends gave, `,
      `-- the fruits and nuts his mother packed with love. `,
      `He regretted his actions and immediately went and apologized to his mother. He also apologized to his friends and as they were good friends, they graciously accepted his apology. He sought forgiveness from his coach and started practicing regularly.
      He felt his game improving session after session. With the help of regular practice, support from friends and coach and nutritious food from his mother he got into the School team once again.`,
    ],
    images: [
      {
        url: "/stories/A Journey Beyond the Pitch_1.png",
        alt: "A Journey Beyond the Pitch",
      },
      {
        url: "/stories/A Journey Beyond the Pitch_2.png",
        alt: "A Journey Beyond the Pitch",
      },
    ],
    theme: "Kindling the Intellect",
    moral: "Manage Vanity Well and Stay rooted in Humility.",
  },
  {
    title: "Prince Siddhartha",
    content: [
      `Prince Siddhartha once awoke to the fact of death, disease and old age in life. To discover the secret of life, he went to a forest and spent his time practicing intense austerities. He practiced intense fasting. His penance was so severe that by the end of his sixth year, he was surviving only on a single grain of rice a day. At one point, he no longer had the strength to meditate. He realized that he would die before he gained liberation due to the ' abuse' he put on his body.`,
      `As he sat under the tree with no strength to continue further he saw two musicians walking nearby. One of them exclaimed that the melody of his lute was just not right. He wondered what was wrong with it. The other musician calmly examined the lute and replied that the musician had tightened the strings too much. As he loosened the string, he told the musician that the strings should not be too tight or too loose . It should be just right. The music then became more melodious.`,
      `Prince Siddhartha now understood that even the path of enlightenment could only be gained neither by being too severe on oneself nor getting spoiled in material pleasures, but only by finding the balance. Then Prince Siddhartha accepted the bowl of food offered to him, which was earlier refused. He slowly regained his strength, renewed his meditation and attained liberation.`,
      `"Yukta- ahara - viharasya yukta- cheshtasya karmasu Yukta- svapna- avabodhasya  yogo bhavathi dukha - ha"`,
      `Bhagawad Gita `,
      `Chapter 6 Sloka- 17`,
      `Meaning - Practising the yoga of maintaining moderation in the habits of eating, sleeping, working and  recreation can mitigate all material pains.`
    ],
    images: [
      {
        url: "/stories/Prince Siddhartha_1.png",
        alt: "Prince Siddhartha",
      },
      {
        url: "/stories/Prince Siddhartha_2.png",
        alt: "Prince Siddhartha",
      },
    ],
    theme: 'Physical fitness',
    moral:
      "The key to balance is to build positive, healthy habits.The key aspects of our life such as eating, exercise, stress management and sleep should be balanced.",
  },
  {
    title: "A Lesson in Staying Cool",
    content: [
      "John McEnroe was one of the greatest tennis players. He has held the World Number One ranking in both singles and doubles. The American tennis champion was notorious and was derailed for his unruly on- court behaviour.",
      `By his own admission, he had anger addiction and he was constantly fined and even suspended for his rage and tantrums on court. Despite his numerous achievements, the world remembers John as a ' Super Brat' for all the vile things he said and did on court.`,
      `When John was only twenty in 1979, ' The Sun' wrote about him as follows: " He is the most vain, ill- tempered, petulant loudmouth that the game of tennis has ever known ". This observation only got validated with time. John McEnroe dug his own grave with his obsessive rage and tantrums.`,
      `• The company of good people, good books and good conversations can alter the content of our thoughts.`,
      `• At the level of speech, observe the words and the language you use regularly. If it is toxic or abusive, change it. Listen more than you speak."`,
      `• At the level of action, set yourself incentives or punishments to break away from repetitive behaviour.`
    ],
    images: [
      {
        url: "/stories/A Lesson in Staying Cool_1.png",
        alt: "A Lesson in Staying Cool",
      },
      {
        url: "/stories/A Lesson in Staying Cool_2.png",
        alt: "A Lesson in Staying Cool",
      },
    ],
    theme: 'Emotional Development',
    moral:
      " When thoughts are repeated,it becomes a habit. When habits are repeated, it becomes behaviour. When behaviour is repeated, it becomes character.",
  },
];

const containerClasses =
  "flex flex-col items-center min-h-screen bg-[#f8f7f6] px-4 font-[family-name:var(--font-geist-sans)]";
const headerClasses =
  "w-full flex justify-between px-4 lg:px-32 items-center py-4 fixed bg-[#f8f7f6]";
const buttonWrapperClasses = "flex items-center gap-2 cursor-pointer";
const buttonClasses =
  "flex items-center gap-2 bg-white rounded-full py-2 px-4 shadow-sm hover:bg-gray-100 transition-colors text-lg text-gray-900 cursor-pointer";

const mic_on =
  typeof Audio !== "undefined" ? new Audio("/sounds/mic_on.mp3") : null;
const mic_off =
  typeof Audio !== "undefined" ? new Audio("/sounds/mic_off.mp3") : null;

export {
  avatarOptions,
  containerClasses,
  headerClasses,
  buttonWrapperClasses,
  buttonClasses,
  moralValues,
  mic_on,
  mic_off,
};
